# 1) build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# copy all projects & sln
COPY ../APBD7.sln .
COPY ../Domain/ Domain/
COPY ../DataAccess/ DataAccess/
COPY ../BusinessLogic/ BusinessLogic/
COPY . ./

# restore and publish WebApi
WORKDIR /src/WebApi
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

# 2) runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "WebApi.dll"]
